#!/usr/bin/env bash

#Parameters file for search_primers.sh

INPUT_FILE="/ngs/microbios/rgallego/good_length.fastq"
OUTPUT_FOLDER="/ngs/microbios/rgallego/pipeline_output/nextera"

BARCODES_i7="/ngs/microbios/rgallego/barcodes_i7_rc.fasta"

BARCODES_i5="/ngs/microbios/rgallego/barcodes_i5.fasta"

METADATA="/ngs/microbios/rgallego/metadata.csv"

# ESTRUCTURA DEL AMPLICON
# 5' p5-i5-NR1-FWD_PRIMER-AMPLICON-REV_PRIMER_RC-NR2_RC-i7_RC-p7_RC 3'
# 5' p7-i7-NR2-REV_PRIMER-AMPLICON-FWD_PRIMER_RC-NR1_RC-i5_RC-p5_RC 3'

# ESTRUCTURA DE LA PRIMERA PCR
# 5' TCGTCGGCAGCGTCAGATGTGTATAAGAGACAG



FWD_PRIMER="AGAGTTTGATCMTGGCTCAG" # Goes after p5 and NR1
FWD_PRIMER_RC="CTGAGCCAKGATCAAACTCT"
REV_PRIMER_RC="AAGTCGTAACAAGGTARCCGTA"
REV_PRIMER="TACGGYTACCTTGTTACGACTT" # Goes after p7 and NR2



NR1="TCGTCGGCAGCGTCAGATGTGTATAAGAGACAG" # Goes after p5
NR1_RC="CTGTCTCTTATACACATCTGACGCTGCCGACGA"
  #      CTGTCTCTTATACACATCTGACGCTGCCGA
NR2="GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAG" # Goes after p7
NR2_RC="CTGTCTCTTATACACATCTCCGAGCCCACGAGAC"
  #     CTGTCTCTTATACACATCTGACGCTGCCGACGA
  #     CTGTCTCTTATACACGTCTAGACCACGACGGCG
p7="CAAGCAGAAGACGGCATACGAGAT"
p7_RC="ATCTCGTATGCCGTCTTCTGCTTG"

p5="AATGATACGGCGACCACCGAGATCTACAC"
p5_RC="GTGTAGATCTCGGTGGTCGCCGTATCATT"
